version: "3.9"

services:
  api:
    build:
      context: .
      target: production
    env_file: [.env]
    ports:
      - "${APP_PORT:-3000}:3000"
    depends_on: [postgres]
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}
  test:
    build:
      context: .
      target: test
    env_file: [.env]
    depends_on: [postgres]
    restart: "no"
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB:       ${DATABASE_NAME}
      POSTGRES_USER:     ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
